# Generated by Django 2.2.16 on 2020-10-29 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='content_key_words',
            field=models.TextField(blank=True, null=True),
        ),
    ]
